#include "statuswords.h"
const tStatusWords SW[] =
{	//3G Status Words---------------------2G Status Words------------------------------Description
	{SEND_GET_RESPONSE					, SIM_SEND_GET_RESPONSE						}, //EXCEP_SEND_GET_RESPONSE
	{RESEND_PREVIOUS_COMMAND			, WRONG_P3									}, //EXCEP_RESEND_COMMAND_WITH_CORRECT_P3
	{NORMAL_ENDING						, NORMAL_ENDING								}, //EXCEP_NORMAL_ENDING - Normal Ending
	{INVALID_CLASS						, INVALID_CLASS								}, //EXCEP_INVALID_CLASS - Wrong class
	{INVALID_INSTRUCTION				, INVALID_INSTRUCTION						}, //EXCEP_INVALID_INS - Wrong Instuction byte
	{WRONG_P1_P2						, WRONG_P1_P2								}, //EXCEP_WRONG_P1_P2 - Wrong P1-P2
	{WRONG_P3							, WRONG_P3									}, //EXCEP_WRONG_P3 - Wrong P3
	{INCORRECT_PARAMS_IN_DATAFIELD		, INCORRECT_PARAMS_IN_DATAFIELD				}, //EXCEP_INCORRECT_DATAFIELD
	{COMMAND_NOT_ALLOWED				, COMMAND_NOT_ALLOWED						}, //EXCEP_COMMAND_NOT_ALLOWED
	{NOT_ENOUGH_MEMORY					, NOT_ENOUGH_MEMORY							}, //EXCEP_NOT_ENOUGH_MEMORY
	{FILE_ID_ALREADY_EXISTS				, FILE_ID_ALREADY_EXISTS					}, //EXCEP_FILE_ID_ALREADY_EXISTS
	{DF_NAME_ALREADY_EXISTS				, DF_NAME_ALREADY_EXISTS					}, //EXCEP_DF_NAME_ALREADY_EXISTS
	{FILE_NOT_FOUND						, SIM_FILE_OR_PATTERN_NOT_FOUND				}, //EXCEP_FILE_NOT_FOUND
	{NO_EF_SELECTED						, SIM_NO_EF_SELECTED						}, //EXCEP_NO_FILE_SELECTED
	{COMMAND_INCOMPATIBLE_WITH_FILE		, SIM_FILE_INCONSISTENT_WITH_COMMAND		}, //EXCEP_INVALID_FILE_TYPE
	{WRONG_P3							, SIM_OUT_OF_RANGE							}, //EXCEP_ADDRESS_OUT_OF_RANGE
	{SECURITY_NOT_SATISIFIED			, SIM_ACCESS_CONDITION_NOT_FULFILLED		}, //EXCEP_SECURITY_NOT_SATISFIED
	{RECORD_NOT_FOUND					, SIM_RECORD_NOT_FOUND						}, //EXCEP_RECORD_NOT_FOUND
	{SELECTED_FILE_INVALIDATED			, SIM_IN_CONTRADICTION_WITH_INVALIDATION	}, //EXCEP_FILE_ALREADY_DEACTIVATED 
	/*why just warning "SELECTED_FILE_INVALIDATED" for  UICC? because if you see the command-sw table in 102221, you will find this status word fall under Select and 
	* Deactivate commands, there is no other reason of throwing this particular Status word in deactivate file. Hence it must be mentioned for this purpose only. 
	*/
	{MAX_VALUE_REACHED_OF_RECORD		, MAX_VALUE_REACHED_OF_RECORD				}, //EXCEP_MAX_VALUE_REACHED
	{NORMAL_ENDING						, SIM_FILE_OR_PATTERN_NOT_FOUND				}, //EXCEP_PATTERN_NOT_FOUND
	{REFERENCED_DATA_INVALIDATED		, SIM_IN_CONTRADICTION_WITH_INVALIDATION	}, //EXCEP_REFERENCED_DATA_INVALIDATED
	{TECHNICAL_PROBLEM					, TECHNICAL_PROBLEM							}, //EXCEP_TECHNICAL_PROBLEM
	{REFERENCED_DATA_NOT_FOUND			, TECHNICAL_PROBLEM							}, //EXCEP_REFERENCED_DATA_NOT_FOUND
	{PIN_VERIFICATION_FAILED			, SIM_PIN_VERIFICATION_FAILED				}, //EXCEP_PIN_VERIFICATION_FAILED
	{AUTHENTICATION_BLOCKED				, SIM_AUTHENTICATION_BLOCKED				}, //EXCEP_PIN_BLOCKED
	{OPERATION_CONTRADICTS_PIN_STATUS	, SIM_IN_CONTRADICTION_WITH_CHV_STATUS		}, //EXCEP_CONTRADICTS_PIN_STATUS
	{PIN_NOT_FOUND						, SIM_PIN_NOT_INITIALIZED					}, //EXCEP_NO_PIN_INITALIZED
	{CONDITIONS_OF_USE_NOT_SATISFIED	, SIM_FILE_INCONSISTENT_WITH_COMMAND		}, //EXCEP_CONDITIONS_OF_USE_NOT_SATISFIED
	{FUNCTION_NOT_SUPPORTED				, WRONG_P1_P2								}, //EXCEP_FUNCTION_NOT_SUPPORTED 
	{LOGICAL_CHANNEL_NOT_SUPPORTED		, INVALID_CLASS								}, //EXCEP_LOGICAL_CHANNEL_NOT_SUPPORTED
	{AUTHENTICATION_ERROR				, AUTHENTICATION_ERROR						}, //EXCEP_INCORRECT_MAC
	{NORMAL_ENDING_PROACTIVE_CMD		, NORMAL_ENDING_PROACTIVE_CMD				}  //EXCEP_NORMAL_END_PENDING_PROACTIVE_CMD
};